version: '3.7'
services:

  app:
    build: ./app
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - database
    networks:
      - postgredatabase_network

  database:
    image: postgres:latest # use latest official postgres version
    env_file:
      - postgres.env # configure postgres
    ports:
      - 5432:5432
    networks:
      - postgredatabase_network
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

networks:
  postgredatabase_network:
    driver: bridge


volumes:
  database-data: # named volumes can be managed easier using docker-compose


